name: ml-software
dependencies:
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py35_0
- h5py=2.6.0=np111py35_1
- hdf5=1.8.16=0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.22=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np111py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.1=py35_0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=1
- pandas=0.18.1=np111py35_0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.2=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_2
- python=3.5.1=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.4=py35_0
- pyyaml=3.11=py35_4
- pyzmq=15.2.0=py35_1
- qt=4.8.7=2
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- scipy=0.17.1=np111py35_0
- seaborn=0.7.0=py35_0
- setuptools=22.0.5=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - keras==1.0.4
  - protobuf==3.0.0b2
  - pyobjc-core==2.5.1
  - pyobjc-framework-accounts==2.5.1
  - pyobjc-framework-addressbook==2.5.1
  - pyobjc-framework-applescriptkit==2.5.1
  - pyobjc-framework-applescriptobjc==2.5.1
  - pyobjc-framework-automator==2.5.1
  - pyobjc-framework-cfnetwork==2.5.1
  - pyobjc-framework-cocoa==2.5.1
  - pyobjc-framework-collaboration==2.5.1
  - pyobjc-framework-coredata==2.5.1
  - pyobjc-framework-corelocation==2.5.1
  - pyobjc-framework-coretext==2.5.1
  - pyobjc-framework-dictionaryservices==2.5.1
  - pyobjc-framework-eventkit==2.5.1
  - pyobjc-framework-exceptionhandling==2.5.1
  - pyobjc-framework-fsevents==2.5.1
  - pyobjc-framework-inputmethodkit==2.5.1
  - pyobjc-framework-installerplugins==2.5.1
  - pyobjc-framework-instantmessage==2.5.1
  - pyobjc-framework-latentsemanticmapping==2.5.1
  - pyobjc-framework-launchservices==2.5.1
  - pyobjc-framework-message==2.5.1
  - pyobjc-framework-opendirectory==2.5.1
  - pyobjc-framework-preferencepanes==2.5.1
  - pyobjc-framework-pubsub==2.5.1
  - pyobjc-framework-qtkit==2.5.1
  - pyobjc-framework-quartz==2.5.1
  - pyobjc-framework-screensaver==2.5.1
  - pyobjc-framework-scriptingbridge==2.5.1
  - pyobjc-framework-searchkit==2.5.1
  - pyobjc-framework-servicemanagement==2.5.1
  - pyobjc-framework-social==2.5.1
  - pyobjc-framework-syncservices==2.5.1
  - pyobjc-framework-systemconfiguration==2.5.1
  - pyobjc-framework-webkit==2.5.1
  - tensorflow==0.9.0rc0
  - theano==0.8.2

